name: ECDSA E2E

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

# Ensures that only a single workflow per PR will run at a time. Cancels in-progress jobs if new commit is pushed.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      DEBUGGING: true
      RUST_BACKTRACE: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Ubuntu packages
        run: sudo apt-get update && sudo apt-get install bash make jq

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Install Docci Readme Runner
        run: |
          VERSION=v0.9.0-beta.2
          wget -O docci.tar.gz "https://github.com/Reecepbcups/docci/releases/download/${VERSION}/docci_Linux_x86_64.tar.gz"
          tar -xzf docci.tar.gz
          sudo mv docci /usr/local/bin/docci
          sudo chmod +x /usr/local/bin/docci
          rm docci.tar.gz

      - run: docci run docker/ECDSA_CLI.md --cleanup-commands="killall anvil || true" --hide-background-logs
